GET http://localhost:3000/todos/
###

// API 1 -- scenario 1
GET http://localhost:3000/todos/?status=TO%20DO/
###
// API 1 -- scenario 2
GET http://localhost:3000/todos/?priority=HIGH/
###
// API 1 -- scenario 3
GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS/
###
// API 1 -- scenario 4
GET http://localhost:3000/todos/?search_q=Play/
###

GET http://localhost:3000/todos/2/ 
###

POST http://localhost:3000/todos/ 
Content-Type: application/json

{
  "id": 11,
  "todo": "LEARN volleyball",
  "priority": "MEDIUM",
  "status": "TO DO"
}
###

// API 4 -- scenario 1

PUT http://localhost:3000/todos/11/
Content-Type: application/json

{
  "status": "DONE"
}
###

// API 4 -- scenario 2

PUT http://localhost:3000/todos/4/
Content-Type: application/json

{
  "priority": "HIGH"
}
###

// API 4 -- scenario 3

PUT http://localhost:3000/todos/11/
Content-Type: application/json

{
  "todo": "Some task"
}
###

DELETE http://localhost:3000/todos/11/